export type AirLabsResponse<T> = {
  request: {};
  response: T;
};

export type AirLabsFlightResponse = {
  aircraft_icao: string;
  airline_iata: string;
  airline_icao: string;
  airline_name: string;
  arr_actual?: string;
  arr_actual_utc?: string;
  arr_baggage: string;
  arr_city: string;
  arr_country: string;
  arr_delayed?: number;
  arr_estimated?: string;
  arr_estimated_utc?: string;
  arr_gate?: string;
  arr_iata: string;
  arr_icao: string;
  arr_name: string;
  arr_terminal: string;
  arr_time: string;
  arr_time_ts: number;
  arr_time_utc: string;
  cs_airline_iata?: string;
  cs_flight_iata?: string;
  cs_flight_number?: string;
  delayed?: number;
  dep_actual: null;
  dep_actual_utc?: string;
  dep_city: string;
  dep_country: string;
  dep_delayed?: number;
  dep_estimated: null;
  dep_estimated_utc?: string;
  dep_gate: string;
  dep_iata: string;
  dep_icao: string;
  dep_name: string;
  dep_terminal: string;
  dep_time: string;
  dep_time_ts: number;
  dep_time_utc: string;
  duration: number;
  flag: string;
  flight_iata: string;
  flight_icao: string;
  flight_number: string;
  percent: number;
  reg_number?: string;
  status: string;
  updated: number;
  utc: string;
};
