version: "3.8"

services:
  db-posgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - "./.db-postgres:/var/lib/postgresql/data"

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   depends_on:
  #     - db-posgres
  #   ports:
  #     - "5555:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   restart: unless-stopped

  # api-server:
  #   depends_on:
  #     - db-posgres
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   # env_file:
  #   # - .env
  #   ports:
  #     - "3000:3000"
  #   # restart: always

volumes:
  postgres-data:
