version: '3.8'

services:
  db-mysql:
    platform: linux/x86_64
    image: mysql:8.0.23
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '3306:${DATABASE_PORT}'
    expose:
      - 3306
    volumes:
      - '../.databases/mysql:/var/lib/mysql'
