name: Fly Deploy Production
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app to production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only -c fly.production.toml
        env:
          NODE_ENV: production
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
