name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  checks: write
  contents: write

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
      ENV: test

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: 'Install dependencies'
        run: bun install --silent

      - name: Generate prisma schema
        run: bun run prisma:generate

      - name: Run tests
        run: bun run test:coverage
